apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phone-book-set-0
  namespace: phone-book-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app: phone-book
  serviceName: "phone-book"
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: phone-book
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: phone-book
        image: vincafd/phone-book:v1
        ports:
        - containerPort: 8888
          name: web
        volumeMounts:
        - name: data
          mountPath: /mnt/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 200Mi
