apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phone-book-set-1
  namespace: phone-book-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: phone-book
  serviceName: "phone-book"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: phone-book
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: phone-book
        image: vincafd/phone-book:v1
        ports:
        - containerPort: 8888
          name: web
        volumeMounts:
        - name: data
          mountPath: /mnt/data
        readinessProbe:
          httpGet:
            path: /api/v1/phonebook?from=100&to=200
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class-2"
      resources:
        requests:
          storage: 200Mi
